[book]
title = "HyprMCP Documentation"
authors = ["Conner Ohnesorge"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = []
additional-js = []
print = { enable = true }
search = { enable = true }
git-repository-url = "https://github.com/conneroisu/hyprmcp"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/conneroisu/hyprmcp/edit/main/docs/{path}"

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false
runnable = false